### PR TITLE
EOS-23184: LR R2 SSPL: Align resource type in sensor/actuator data with that of Node Health - Server

### PR DESCRIPTION
**Pull request by mariyappanp**
…th that of Node Health - Server

## Coding:

* [x] Did you follow coding standard and verified it with flake8? 

* [x] Did your address all Codacy issues?

## Testing:

* [x] Unittest updated and all unittests are passing?

* [x] Sanity/Self tests are updated (if applicable)?

* [x] Manual testing done covering happy path and non-happy path?

## Integration:

* [x] If there is any interface change, did you communicate it to other components?
* [ ] If there is any interface change, other componenent gate gatekeepers are ready to accept the change?
* [ ] Did you complete deployment test if applicable?

## PR checklist:
* [x] Did you add Jira number to the PR?

* [x] DCO and cla-signed?

### CODE REVIEW

**Review by shriya-deshmukh — APPROVED** [review]

**Review by gargpalak048 — APPROVED** [review]
LGTM

**Review by sumedhak27 — APPROVED** [review]

**Review by sumedhak27 — APPROVED** [review]
Now, we have `server:hw:disk` resource type in 2 sensors, node_data, node_hw and disk_monitor..Bit confusing for me..😅

**Comment by mariyappanp** [comment]
> Now, we have `server:hw:disk` resource type in 3 sensors, node_data, node_hw, and disk_monitor..A bit confusing for me..😅

Right. 
Earlier `node:hw:disk` was present in node_hw and node_data. IPMITOOL result is processed and carried with this.
`node:os:disk` in disk_monitor is based on SMARTCTL result.
Now all these three are aligned to node health resource types. In node health we don't have resource specific to os.

@cdeshmukh please confirm that we need to keep os based resource types still.

**Review by cdeshmukh — APPROVED** [review]
LGTM, though we had decided to deliver it in a feature branch than main, given CSM also needs to regress/adopt it too, or we may end up breaking end-to-end flow. Can we do that now

**Review by sandeepsgt — APPROVED** [review]

**Pull request merged**
