### PR TITLE
Welcome bot for contributors

### PR DESCRIPTION
**Pull request by VenkyOS**
Signed-off-by: Venkataraman Padmanabhan <venkataraman.padmanabhan@seagate.com>

## Problem Statement
<pre>
  <code>
    Story Ref (if any):
   
     A GitHub bot that welcomes new users based off maintainer defined comments that must be located in .github/config.yml

     It combines 3 plugins which has already being tested in CORTX repo,

     - new-issue-welcome

     - new-pr-welcome
     
     - first-pr-merge

  </code>
</pre>
## Problem Description
<pre>
  <code>
    Please add Problem decription here...
  </code>
</pre>
## Solution
<pre>
  <code>
    Please add summary of the change,List any dependencies that are required for this change.
  </code>
</pre>
## Sanity testing on RPM done
<pre>
  <code>
    - [ ] Yes
    - [ ] No
  </code>
</pre>
## Unit/Manual Testing Description
<pre>
  <code>
    Please describe the tests that you ran to verify your changes.
  </code>
</pre>

### CODE REVIEW

**Comment by mukul-seagate11** [comment]
please review & update the PR

**Review by cdeshmukh — APPROVED** [review]

**Review by thavanathan — CHANGES_REQUESTED** [review]
Please sign-off the code and rebase.

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by VenkyOS** [comment]
> Please sign-off the code and rebase.

Incorporated

**Review by thavanathan — APPROVED** [review]

**Review by thavanathan — APPROVED** [review]

**Pull request merged**
